name: get id test

on:
  push:
    branches:
      - Beta

jobs:
  run_python_script:
    name: get id test
    runs-on: windows-latest  # Use the latest version of Windows

    steps:
      - name: Get Job ID from GH API
        id: get-job-id
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs)
          echo $jobs

      - name: Display Job ID
        run: |
          echo Job ID: ${{ steps.get-job-id.outputs.job_id }}
          echo My full job URL is ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ steps.get-job-id.outputs.job_id }}