name: get id test

on:
  push:
    branches:
      - Beta

jobs:
  run_python_script:
    name: get id test
    runs-on: windows-latest  # Use the latest version of Windows

    steps:
      - name: Parse job_id
        shell: bash
        run: |
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/attempts/${GITHUB_RUN_ATTEMPT}/jobs | jq .jobs[].id