name: Test runner

on: workflow_dispatch

jobs:
  run_python_script:
    name: Test runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the repository's code


      - name: Set up Python
        uses: actions/setup-python@v5  # Set up Python environment
        with:
              python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r Utils/requirements.txt 
          
      - uses: browser-actions/setup-chrome@latest

      - uses: browser-actions/setup-edge@latest

      - uses: browser-actions/setup-firefox@latest

      - name: Create Login Tokens
        env:
          COOKIES: ${{ secrets.COOKIES }}
        run: python ./Utils/Create_Tokens.py

      - name: Start Selenium Server HUB
        run: nohup java -jar ./Utils/selenium-server.jar hub & sleep 10
        shell: bash

      - name: Start Selenium Server nodes
        run: nohup java -jar ./Utils/selenium-server.jar node --port 5555 --selenium-manager true & sleep 10
        shell: bash

      - name: Running Tests
        run: python .Test_Runner.py

      - name: Upload Tests reports
        uses: actions/upload-artifact@v2
        with:
          name: Upload Tests reports
          path: ./Results


      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages


      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history


      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history


      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: jameel978.github.io/Steam-Automation-Project/${{ github.run_number }}