name: Test runner

on: workflow_dispatch

jobs:
  run_python_script:
    name: Test runner
    runs-on: windows-latest  # Use the latest version of Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the repository's code

      - name: Set up Python
        uses: actions/setup-python@v5  # Set up Python environment
        with:
              python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r Utils/requirements.txt  # Install dependencies if needed
          
      - uses: browser-actions/setup-chrome@latest

      - uses: browser-actions/setup-edge@latest

      - uses: browser-actions/setup-firefox@latest

      - name: prepare Tokens
        env:
          COOKIES: ${{ secrets.COOKIES }}

        run: python Utils/Create_Tokens.py

      - name: Running Selenium Tests
        run: python Selenium_test_runner.py

      - name: Running API Tests
        run: python API_Test_runner.py
